server:
  port: 8080
  servlet:
    context-path: /websocketdemo

spring:
  rabbitmq:
    #rabbitHost: 192.168.153.136
    #rabbitPort: 5672
    #rabbitUser: guest
    #rabbitPass: guest
    host: 192.168.153.136
    username: guest
    password: guest
    port: 5672





